"""UIAutomation wrapper module — COM client, controls, and patterns."""

from .core import (
    GA_ROOT,
    INPUT,
    INPUT_KEYBOARD,
    INPUT_MOUSE,
    INPUT_UNION,
    KEYBDINPUT,
    KEYEVENTF_KEYUP,
    KEYEVENTF_UNICODE,
    MOUSEEVENTF_ABSOLUTE,
    MOUSEEVENTF_LEFTDOWN,
    MOUSEEVENTF_LEFTUP,
    MOUSEEVENTF_MIDDLEDOWN,
    MOUSEEVENTF_MIDDLEUP,
    MOUSEEVENTF_MOVE,
    MOUSEEVENTF_RIGHTDOWN,
    MOUSEEVENTF_RIGHTUP,
    MOUSEEVENTF_WHEEL,
    MOUSEINPUT,
    SW_RESTORE,
    _AutomationClient,
    get_automation_client,
    send_input,
    user32,
)
from .controls import (
    click_at,
    enumerate_windows,
    get_foreground_window,
    get_root_window,
    get_window_class,
    get_window_pid,
    get_window_rect,
    get_window_title,
    is_window_visible,
    move_cursor,
    move_window,
    scroll_at,
    set_foreground_window,
    type_text,
)
from .patterns import (
    get_element_from_handle,
    get_element_from_point,
    get_element_rect,
    try_invoke,
    try_set_value,
)

__all__ = [
    # core
    "GA_ROOT",
    "INPUT",
    "INPUT_KEYBOARD",
    "INPUT_MOUSE",
    "INPUT_UNION",
    "KEYBDINPUT",
    "KEYEVENTF_KEYUP",
    "KEYEVENTF_UNICODE",
    "MOUSEEVENTF_ABSOLUTE",
    "MOUSEEVENTF_LEFTDOWN",
    "MOUSEEVENTF_LEFTUP",
    "MOUSEEVENTF_MIDDLEDOWN",
    "MOUSEEVENTF_MIDDLEUP",
    "MOUSEEVENTF_MOVE",
    "MOUSEEVENTF_RIGHTDOWN",
    "MOUSEEVENTF_RIGHTUP",
    "MOUSEEVENTF_WHEEL",
    "MOUSEINPUT",
    "SW_RESTORE",
    "_AutomationClient",
    "get_automation_client",
    "send_input",
    "user32",
    # controls
    "click_at",
    "enumerate_windows",
    "get_foreground_window",
    "get_root_window",
    "get_window_class",
    "get_window_pid",
    "get_window_rect",
    "get_window_title",
    "is_window_visible",
    "move_cursor",
    "move_window",
    "scroll_at",
    "set_foreground_window",
    "type_text",
    # patterns
    "get_element_from_handle",
    "get_element_from_point",
    "get_element_rect",
    "try_invoke",
    "try_set_value",
]
